#!/bin/bash
#
# http://stackoverflow.com/questions/10768160/ip-address-converter
#

dec2ip () {
  local ip dec=$@
  for e in {3..0}
  do
    ((octet = dec / (256 ** e) ))
    ((dec -= octet * 256 ** e))
    ip+=$delim$octet
    delim=.
  done
  printf '%s\n' "$ip"
}

# #!/usr/bin/awk -f
# # dec2ip
# BEGIN {
#   dec = ARGV[1]
#   for (e = 3; e >= 0; e--) {
#     octet = int(dec / (256 ^ e))
#     dec -= octet * 256 ^ e
#     ip = ip delim octet
#     delim = "."
#   }
#   printf("%s\n", ip)
# }
